- Numpy is a package used for math operations


- Numpy means numerical python


- Because of Numpy we can create multi dimensional data


- Data represents in form of list or tuple


- same as data represents in multipule ways

    - **List** : does not have any dimensions
    
    - **Array** : Has dimensions created by numpy,mostly used in ML
    
    - **Tensors** : Has dimensions also vector representations created by tensorflow in DL NLP AI    
    
    - **Torch** : also another form of vectors created by torch in DL NLP AI

In [2]:
[1,2,3,4]
array([1,2,3,4])  # CPU support but not gpu
tensor([1,2,3,4]) # CPU and GPU support 

In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

In [ ]:
# Note : Numpy is a very powerful module
#      the versions are impact on another modules
#      some times we might be increas the version or decrease the version

**Create an array**

In [6]:
list1 = [1,2,3,4]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.ndim

1

In [10]:
np.array([1,2,3])
np.array([1,2,3],[10,20,30])
np.array([[1,2,3],[10,20,30]])

l1 = [1,2,3]
l2 = [10,20,30]
np.arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [14]:
arr2 = np.array([[1,2,3],[10,20,30]])
arr2.ndim

2

In [15]:
arr3 = np.array([[1,2,3],[10,20,30],[100,200,300]])
arr3.ndim

2

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.ndim

1

In [14]:
arr3 = np.array([[[1,2,3],[10,20,30],[100,200,300]]])

In [15]:
arr3.ndim

3

In [25]:
arr2 = np.array([[1,2,3],[10,20,30]])

In [26]:
arr2.ndim

2

In [30]:
arr2_1 = np.array([[[1,2,3],[10,20,30]]])

In [32]:
arr2_1.ndim

3

In [33]:
arr4 = np.array([[[[1,2,3],[10,20,30]]]])

In [34]:
arr4.ndim

4

In [35]:
arr1

array([1, 2, 3, 4])

In [36]:
arr2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [38]:
arr2_1

array([[[ 1,  2,  3],
        [10, 20, 30]]])

In [39]:
arr3

array([[[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]]])

In [40]:
arr4

array([[[[ 1,  2,  3],
         [10, 20, 30]]]])

In [41]:
arr1.shape

(4,)

In [42]:
arr2.shape

(2, 3)

In [43]:
arr2_1.shape

(1, 2, 3)

In [44]:
arr3.shape

(1, 3, 3)

In [45]:
arr4.shape

(1, 1, 2, 3)

In [66]:
arr4_1 = np.array([[[1,2,3],
                   [10,20,30]],
                [[1,2,3],
                   [10,20,30]]])

In [67]:
arr4_1.shape

(2, 2, 3)

In [68]:
arr4_1

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 1,  2,  3],
        [10, 20, 30]]])

In [71]:
arr4_2 = np.array([[
                    [
                        [1,2,3,4],
                   [10,20,30,40],
                [100,200,300,400]
                    ],
    
                [
                    [1,2,3,4],
                   [10,20,30,40],
                [100,200,300,400]
                ]
]])

In [72]:
arr4_2.shape

(1, 2, 3, 4)

In [73]:
arr4_2

array([[[[  1,   2,   3,   4],
         [ 10,  20,  30,  40],
         [100, 200, 300, 400]],

        [[  1,   2,   3,   4],
         [ 10,  20,  30,  40],
         [100, 200, 300, 400]]]])