In [3]:
l1 = [1,2,3]
l2 = [10,20,30]
l = []
for i in range(len(l1)):
    l.append(l1[i] +l2[i])
l

[11, 22, 33]

In [4]:
[i+j for i,j in zip(l1,l2)]

[11, 22, 33]

In [5]:
import numpy as np

In [7]:
arr1 = np.array(l1)
arr2 = np.array(l2)

In [8]:
arr1+arr2

array([11, 22, 33])

- element wise operation works in numpy


In [9]:
arr1*arr2

array([10, 40, 90])

In [10]:
arr1/arr2

array([0.1, 0.1, 0.1])

**how to convert array to list**

In [11]:
arr1

array([1, 2, 3])

In [14]:
list(arr1)    # type casting

[1, 2, 3]

In [15]:
arr1.tolist()

[1, 2, 3]

**speed analysis**

In [17]:
# take tow list of 1000 numbers
# multiply those
# calculate the time process

# take tow arrays of 1000 numbers
# multiply those
# calculate the time process

In [3]:
import time
start = time.time()
l1 = range(1,10000)
l2 = range(1,10000)
[i*j for i,j in zip(l1,l2)]
end = time.time()
print('time taking is:',(end-start))

time taking is: 25.907930374145508


In [4]:
import time
import numpy as np
start = time.time()
arr1 = np.arange(1,100000000)
arr2 = np.arange(1,100000000)
[i*j for i,j in zip(l1,l2)]
end = time.time()
print('time taking is:',(end-start))

time taking is: 29.036244869232178


- len

- min

- max

- sum

- count

- mean

- median

- mode

- variance

- standard deviation

- covariance

- correlation

- percentile

- quartile